# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 09:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_time', models.DateField()),
                ('remind_title', models.CharField(max_length=30)),
                ('remind_content', models.CharField(max_length=200)),
                ('remind_only_onece', models.BooleanField()),
                ('remind_receiver_email', models.EmailField(max_length=254)),
                ('remind_sender_email', models.EmailField(default=b'raoqilin01@163.com', max_length=254)),
                ('user_ame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
