# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20161211_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='remind_time',
            field=models.DateTimeField(),
        ),
    ]
