# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20161211_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='remind_time',
            field=models.TimeField(),
        ),
    ]
