# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20161211_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='remind_receiver_email',
            field=models.EmailField(default='hwtest0001@163.com', max_length=254),
            preserve_default=False,
        ),
    ]
